### ISSUE TITLE
composer init > command not found

### ISSUE THREAD

**Issue by augustogoncalves** [JohnOnSoftware/forge.learning#5]
composer installs, by default, on the current folder, therefore it doesn't work for other places. 

when I tried `composer init` I got `command not found`, but [after this suggestion](https://stackoverflow.com/a/25022888), it worked. 

maybe add a troubleshooting paragraph?

**Comment by JohnOnSoftware** [comment]
Add a note at environment/tools/php, along with installing Composer,

**Comment by augustogoncalves** [comment]
closed, but see #10
